---
kind: pipeline
name: build
type: kubernetes

steps:
- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nold360/borgserver
    dockerfile: Dockerfile
    tags:
      - bullseye
      - 1.1.16
