---
kind: pipeline
name: build
type: kubernetes

steps:
- name: build-bookworm
  image: plugins/kaniko
  environment:
    # Workaround for Kanikos container detection
    container: docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nold360/borgserver
    dockerfile: Dockerfile
    build_args:
      - BASE_IMAGE=debian:bookworm-slim
    tags:
      - bookworm
      - 1.2.1

- name: build-bullseye
  image: plugins/kaniko
  environment:
    # Workaround for Kanikos container detection
    container: docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nold360/borgserver
    dockerfile: Dockerfile
    build_args:
      - BASE_IMAGE=debian:bullseye-slim
    tags:
      - latest
      - bullseye
      - 1.1.16

- name: build-buster
  image: plugins/kaniko
  environment:
    # Workaround for Kanikos container detection
    container: docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nold360/borgserver
    dockerfile: Dockerfile
    build_args:
      - BASE_IMAGE=debian:buster-slim
    tags:
      - buster
      - 1.1.9
